version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "vitest",
    "jest"
  ]
  dialect = "flow"
  style_guide = "standard"

[[transformers]]
name = "prettier"
